
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightPOWERrightROOTleftTIMESDIVIDEleftPLUSMINUSDIVIDE LPAR MINUS NUMBER PLUS POWER ROOT RPAR TIMESS : EE : E PLUS T\n         | E MINUS T\n         | TT : T TIMES F\n         | T DIVIDE F\n         | FF : NUMBER\n         | LPAR E RPAR\n         | F POWER F\n         | F ROOT F'
    
_lr_action_items = {'NUMBER':([0,6,7,8,9,10,11,12,],[5,5,5,5,5,5,5,5,]),'LPAR':([0,6,7,8,9,10,11,12,],[6,6,6,6,6,6,6,6,]),'$end':([1,2,3,4,5,14,15,16,17,18,19,20,],[0,-1,-4,-7,-8,-2,-3,-5,-6,-10,-11,-9,]),'PLUS':([2,3,4,5,13,14,15,16,17,18,19,20,],[7,-4,-7,-8,7,-2,-3,-5,-6,-10,-11,-9,]),'MINUS':([2,3,4,5,13,14,15,16,17,18,19,20,],[8,-4,-7,-8,8,-2,-3,-5,-6,-10,-11,-9,]),'RPAR':([3,4,5,13,14,15,16,17,18,19,20,],[-4,-7,-8,20,-2,-3,-5,-6,-10,-11,-9,]),'TIMES':([3,4,5,14,15,16,17,18,19,20,],[9,-7,-8,9,9,-5,-6,-10,-11,-9,]),'DIVIDE':([3,4,5,14,15,16,17,18,19,20,],[10,-7,-8,10,10,-5,-6,-10,-11,-9,]),'POWER':([4,5,16,17,18,19,20,],[11,-8,11,11,11,-11,-9,]),'ROOT':([4,5,16,17,18,19,20,],[12,-8,12,12,12,12,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,6,],[2,13,]),'T':([0,6,7,8,],[3,3,14,15,]),'F':([0,6,7,8,9,10,11,12,],[4,4,4,4,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_s','sintatico.py',14),
  ('E -> E PLUS T','E',3,'p_e','sintatico.py',19),
  ('E -> E MINUS T','E',3,'p_e','sintatico.py',20),
  ('E -> T','E',1,'p_e','sintatico.py',21),
  ('T -> T TIMES F','T',3,'p_t','sintatico.py',28),
  ('T -> T DIVIDE F','T',3,'p_t','sintatico.py',29),
  ('T -> F','T',1,'p_t','sintatico.py',30),
  ('F -> NUMBER','F',1,'p_f','sintatico.py',37),
  ('F -> LPAR E RPAR','F',3,'p_f','sintatico.py',38),
  ('F -> F POWER F','F',3,'p_f','sintatico.py',39),
  ('F -> F ROOT F','F',3,'p_f','sintatico.py',40),
]
