
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightEQUALSrightPOWERrightROOTleftTIMESDIVIDEleftPLUSMINUSDIVIDE EQUALS LPAR MINUS NUMBER PLUS POWER ROOT RPAR TIMES VARS : ES : VAR EQUALS EE : E PLUS T\n| E MINUS T\n| TT : T TIMES F\n| T DIVIDE F\n| FF : NUMBER\n| VAR\n| LPAR E RPAR\n| F POWER F\n| F ROOT F'
    
_lr_action_items = {'VAR':([0,7,8,9,10,11,12,13,14,],[3,16,16,16,16,16,16,16,16,]),'NUMBER':([0,7,8,9,10,11,12,13,14,],[6,6,6,6,6,6,6,6,6,]),'LPAR':([0,7,8,9,10,11,12,13,14,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,4,5,6,16,17,18,19,20,21,22,23,24,],[0,-1,-10,-5,-8,-9,-10,-3,-4,-2,-6,-7,-12,-13,-11,]),'PLUS':([2,3,4,5,6,15,16,17,18,19,20,21,22,23,24,],[8,-10,-5,-8,-9,8,-10,-3,-4,8,-6,-7,-12,-13,-11,]),'MINUS':([2,3,4,5,6,15,16,17,18,19,20,21,22,23,24,],[9,-10,-5,-8,-9,9,-10,-3,-4,9,-6,-7,-12,-13,-11,]),'EQUALS':([3,],[10,]),'POWER':([3,5,6,16,20,21,22,23,24,],[-10,13,-9,-10,13,13,13,-13,-11,]),'ROOT':([3,5,6,16,20,21,22,23,24,],[-10,14,-9,-10,14,14,14,14,-11,]),'TIMES':([3,4,5,6,16,17,18,20,21,22,23,24,],[-10,11,-8,-9,-10,11,11,-6,-7,-12,-13,-11,]),'DIVIDE':([3,4,5,6,16,17,18,20,21,22,23,24,],[-10,12,-8,-9,-10,12,12,-6,-7,-12,-13,-11,]),'RPAR':([4,5,6,15,16,17,18,20,21,22,23,24,],[-5,-8,-9,24,-10,-3,-4,-6,-7,-12,-13,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,7,10,],[2,15,19,]),'T':([0,7,8,9,10,],[4,4,17,18,4,]),'F':([0,7,8,9,10,11,12,13,14,],[5,5,5,5,5,20,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_s','semantico.py',18),
  ('S -> VAR EQUALS E','S',3,'p_assignment','semantico.py',23),
  ('E -> E PLUS T','E',3,'p_e','semantico.py',28),
  ('E -> E MINUS T','E',3,'p_e','semantico.py',29),
  ('E -> T','E',1,'p_e','semantico.py',30),
  ('T -> T TIMES F','T',3,'p_t','semantico.py',37),
  ('T -> T DIVIDE F','T',3,'p_t','semantico.py',38),
  ('T -> F','T',1,'p_t','semantico.py',39),
  ('F -> NUMBER','F',1,'p_f','semantico.py',50),
  ('F -> VAR','F',1,'p_f','semantico.py',51),
  ('F -> LPAR E RPAR','F',3,'p_f','semantico.py',52),
  ('F -> F POWER F','F',3,'p_f','semantico.py',53),
  ('F -> F ROOT F','F',3,'p_f','semantico.py',54),
]
